version: "3.8"

services:
  elastic:
    image: elasticsearch:8.6.2
    container_name: elasticsearch
    restart: always
    environment:
      xpack.security.enabled: 'false'
      ES_JAVA_OPTS: -Xms600m -Xmx600m
      discovery.type: single-node
    ports:
    - 9200:9200

  elastic_start:
      build: ./src/services/elastic_start
      container_name: postgres_to_es
      depends_on:
        - elastic
      env_file:
        - ./.env
      volumes:
        - ./index.json:/usr/src/app/index.json
        - ./dump_elastic.json:/usr/src/app/dump_elastic.json