version: "3.8"

services:
  db:
    image: postgres:15.2-alpine
    container_name: postgres_elastic
    restart: always
    env_file:
      - ./.env.db
    volumes:
      - ./movies_db.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - 5432

  etl_genre:
    container_name: etl_genre
    build: ./etl_genres
    restart: always
    env_file:
      - ./etl_genres/.env.docker

  etl_person:
    container_name: etl_person
    build: ./etl_persons
    restart: always
    env_file:
      - ./etl_persons/.env.etl

  elastic:
    image: elasticsearch:8.6.2
    container_name: elasticsearch
    restart: always
    environment:
      xpack.security.enabled: 'false'
      ES_JAVA_OPTS: -Xms600m -Xmx600m
      discovery.type: single-node
    expose:
      - 9200

  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    expose:
      - 6379

  elastic_start:
      build: ./elastic_start
      container_name: elastic_start
      depends_on:
        - elastic
      env_file:
        - ./.env
      volumes:
        - ./index.json:/usr/src/app/index.json
        - ./dump_elastic.json:/usr/src/app/dump_elastic.json

  fast_api:
      build: ./src
      container_name: fast_api
      restart: always
      depends_on:
        - elastic
        - redis
      env_file:
        - ./.env
      expose:
      - 8000

  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    depends_on:
      - fast_api
    ports:
      - 80:80
    volumes:
      - ./nginx_config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx_config/site.conf:/etc/nginx/conf.d/site.conf:ro