version: "3.8"

services:
  elastic:
    image: elasticsearch:8.6.2
    container_name: elasticsearch
    restart: always
    environment:
      xpack.security.enabled: 'false'
      ES_JAVA_OPTS: -Xms600m -Xmx600m
      discovery.type: single-node
    ports:
    - 9200:9200