version: "3.8"

services:
  db:
    image: postgres:15.2-alpine
    container_name: postgres_elastic
    restart: always
    env_file:
      - ./.env.db
    volumes:
      - ./movies_db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5438:5432