version: "3.8"

services:
  db:
    image: postgres:15.2-alpine
    container_name: postgres_elastic
    restart: always
    env_file:
      - ./.env.db
    volumes:
      - ./movies_db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5438:5432

  etl_genre:
    build: ./etl_genres
    restart: always
    env_file:
      - ./etl_genres/.env.docker

  etl_person:
    build: ./etl_persons
    restart: always
    env_file:
      - ./etl_persons/.env.etl

  elastic:
    image: elasticsearch:8.6.2
    container_name: elasticsearch
    restart: always
    environment:
      xpack.security.enabled: 'false'
      ES_JAVA_OPTS: -Xms600m -Xmx600m
      discovery.type: single-node
    ports:
    - 9200:9200

  elastic_start:
      build: ./src/services/elastic_start
      container_name: elastic_start
      depends_on:
        - elastic
      env_file:
        - ./.env
      volumes:
        - ./index.json:/usr/src/app/index.json
        - ./dump_elastic.json:/usr/src/app/dump_elastic.json